
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-07
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjg1OTgwOTEz","is_bot":false,"login":"hannahz0","name":"Hannah Zhang"},"headRefName":"hz-rosterstudentform","number":39,"title":"hz - add form for roster students","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-07/pull/39"},{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"stuRoster-delete","number":38,"title":"Add DELETE endpoint for student roster controller","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-07/pull/38"},{"author":{"id":"U_kgDOB2-uaQ","is_bot":false,"login":"stevenliu2002","name":"Yuchen Liu"},"headRefName":"steven-courses-list","number":37,"title":"yl - add backend list endpoint for CoursesController and tests","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-07/pull/37"},{"author":{"id":"U_kgDOB3D7gA","is_bot":false,"login":"linzezhou","name":"LINZE ZHOU"},"headRefName":"stuRoster-put","number":35,"title":"Add PUT (update) for student roster controller plus tests","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-07/pull/35"},{"author":{"id":"U_kgDOB7-UXw","is_bot":false,"login":"zhushelly","name":"Shelly Zhu"},"headRefName":"sz-admin-table","number":34,"title":"sz-Create Admin table (entity and repository)","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-07/pull/34"}]
